### Gradiente por descenso
#### Equipo No. 6: Elena Villalobos Nolasco, Carolina Acosta Tovany y Aide Jazmín González Cruz

In [ ]:
#### 1.- Se importan los paquetes

In [1]:
import random
import csv
import numpy as np
import pandas as pd

In [2]:
def costo(teta,teta0,data,n):#Función Objetivo J(Ø,Ø0)
    suma = np.array([0.0])
    yi = 0
    
    for i in data:
        if(i[4] == 0):
            yi = -1
        else:
            yi = 1
                
        x = i[:len(i)-1]
        suma = yi * ((np.dot(np.array(teta).transpose(),np.array(x))) + teta0)
        
        if suma < 1:
            Lh = -1
        else:
            Lh = 0
        
        suma =  suma + Lh * yi
            
    return ((1/n)*suma)

def descenso_x_gradiente(data, eta, Oini, O0ini, lamda):
        # Se crea arreglo para guardar los pesos que se van calculando
        O = []
        O0 = []
        O.append(Oini)
        O0.append(O0ini)
        
        Ot = []
        Ot0 = []
        
        n = len(data)
        t = 0
        
        my_list = [1,2]
        
        #while True:  
        for j in my_list:
            t = t + 1
            sumaO = np.array([0.0, 0.0, 0.0, 0.0])
            sumaO0 = np.array([0.0])
            #for i in data:
            for i in data:
                print(i)
                print('i[4]: ' + str(i[4]))
                if(i[4] == 0):
                    yi = -1
                else:
                    yi = 1
                    
                x = i[:len(i)-1]
                print('x: ' + str(x))
                #Valida esta parte y(i)(Ø(t-1)Tx(i)+Ø0(t-1)) 
                print('O: ' + str(O[t-1]))
                print(np.array(x).transpose())
                print(np.dot(np.array(O[t-1]).transpose(),np.array(x)))
                print(O0[t-1])
                hip = yi * ((np.dot(np.array(O[t-1]).transpose(),np.array(x))) + O0[t-1])
                print('hip: ' + str(hip))
                val = 0.0
                if(hip < 1):
                    val = -1
                else:
                    val = 0.0
                    
                hip_O = val * ((yi * np.array(x)) + (lamda * O[t-1]))
                print('hip_O: ' + str(hip_O))
                hip_O0 = val * yi
                print('hip_O0: ' + str(hip_O0))
                
                sumaO = sumaO + hip_O
                print('sumaO: ' + str(sumaO))
                sumaO0 = sumaO0 + hip_O0
                print('sumaO0: ' + str(sumaO0))
                print('End for --------------------------------')
         
            Ot = O[t-1] - eta * ((1/n)*sumaO)
            print('Ot:' + str(Ot))
            Ot0 = O0[t-1] - eta * (((1/n)*sumaO0))
            print('Ot0:' + str(Ot0))
                                 
            O = np.insert(O, 1, Ot, axis=0)
            O0 = np.insert(O0, 1, Ot0, axis=0)
           
                                 
            cost = abs(costo(O[t],O0[t],data,n) - costo(O[t-1],O0[t-1],data,n))     
            print('cost: ' + str(cost))
        #epsilon = 0.05                         
        #if( cost < 0.05):
         #   break 
            print(str(Ot) + ' *** ' + str(Ot0))
            print('End while ---------------------------------------------------------------------')
        #return Ot, Ot0
        
        
def load_data(path, header):
    marks_df = pd.read_csv(path, header=header)
    return marks_df

data = load_data("iris_num.txt",None)
data = np.array(data)

In [3]:
#data_iris_setosa = data[0:50]
#data_iris_no_setosa = data[50:150]

#data_with_two_species = data_iris_setosa + data_iris_no_setosa
    
#Reordenando datos aleatoriamente
random.shuffle(data)

#Datos de entrenamiento
datos_entrenamiento = data[0:2]

#Datos de verificación
data_validacion = data[:-30]

#Llamando a gradiente por descenso
eta = 0.1
Oini = np.array([0.0, 0.0, 0.0, 0.0])
O0ini = np.array([0.0])
lamda = 0.1

print(datos_entrenamiento)
descenso_x_gradiente(datos_entrenamiento, eta, Oini, O0ini, lamda)

[[5.1 3.5 1.4 0.2 1. ]
 [5.1 3.5 1.4 0.2 1. ]]
[5.1 3.5 1.4 0.2 1. ]
i[4]: 1.0
x: [5.1 3.5 1.4 0.2]
O: [0. 0. 0. 0.]
[5.1 3.5 1.4 0.2]
0.0
[0.]
hip: [0.]
hip_O: [-5.1 -3.5 -1.4 -0.2]
hip_O0: -1
sumaO: [-5.1 -3.5 -1.4 -0.2]
sumaO0: [-1.]
End for --------------------------------
[5.1 3.5 1.4 0.2 1. ]
i[4]: 1.0
x: [5.1 3.5 1.4 0.2]
O: [0. 0. 0. 0.]
[5.1 3.5 1.4 0.2]
0.0
[0.]
hip: [0.]
hip_O: [-5.1 -3.5 -1.4 -0.2]
hip_O0: -1
sumaO: [-10.2  -7.   -2.8  -0.4]
sumaO0: [-2.]
End for --------------------------------
Ot:[0.51 0.35 0.14 0.02]
Ot0:[0.1]
cost: [2.563]
[0.51 0.35 0.14 0.02] *** [0.1]
End while ---------------------------------------------------------------------
[5.1 3.5 1.4 0.2 1. ]
i[4]: 1.0
x: [5.1 3.5 1.4 0.2]
O: [0.51 0.35 0.14 0.02]
[5.1 3.5 1.4 0.2]
4.026
[0.1]
hip: [4.126]
hip_O: [0. 0. 0. 0.]
hip_O0: 0.0
sumaO: [0. 0. 0. 0.]
sumaO0: [0.]
End for --------------------------------
[5.1 3.5 1.4 0.2 1. ]
i[4]: 1.0
x: [5.1 3.5 1.4 0.2]
O: [0.51 0.35 0.14 0.02]
[5.1 3.5 1.4 0.2]
4